[mseedlite] Fix error in non-STEIM encodings
When writing out a miniseed record using a non-STEIM encoding, recent
versions of mseedlite raise an error due to an unset attribute X0:

      File "/opt/seiscomp/lib/python/seiscomp/mseedlite.py", line 612, in write
        + struct.pack(">ll", self.X0, self.Xn)
                             ^^^^^^^
    AttributeError: 'Record' object has no attribute 'X0'

Looks like the regression was in
77fa2a115396f4f82e499fbd561c394088cb8510, which added an early return so
that self.X0 and self.Xn are set only for STEIM-encoded records. This
makes sense (since X0 and Xn are STEIM-specific parameters) but
inadvertently broke .write (which was using X0 and Xn to reconstruct the
original bytes in this case).

My fix here seems the most natural solution: just write out the original
self.data for non-STEIM encodings.